# Generated by Django 4.2.7 on 2024-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy_diet_planner_app', '0003_alter_fooditem_mealtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='mealType',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
